// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXm3PHrgFO9WR319FhXl59ttOWJLlvBOg',
    appId: '1:875525409377:web:80137fb0e373956a0e3820',
    messagingSenderId: '875525409377',
    projectId: 'aula0910-efa77',
    authDomain: 'aula0910-efa77.firebaseapp.com',
    storageBucket: 'aula0910-efa77.firebasestorage.app',
    measurementId: 'G-DG4VYJGST1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0gyX2hZzjAUm7RkOo5fIBCAHLnxILtk',
    appId: '1:875525409377:android:ff471151014e5a620e3820',
    messagingSenderId: '875525409377',
    projectId: 'aula0910-efa77',
    storageBucket: 'aula0910-efa77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzidTkmL5Xho5opUc2ndl__oOxEgFHQg',
    appId: '1:875525409377:ios:c4909828598d2d9c0e3820',
    messagingSenderId: '875525409377',
    projectId: 'aula0910-efa77',
    storageBucket: 'aula0910-efa77.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuzidTkmL5Xho5opUc2ndl__oOxEgFHQg',
    appId: '1:875525409377:ios:c4909828598d2d9c0e3820',
    messagingSenderId: '875525409377',
    projectId: 'aula0910-efa77',
    storageBucket: 'aula0910-efa77.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXm3PHrgFO9WR319FhXl59ttOWJLlvBOg',
    appId: '1:875525409377:web:a2639716bb85f52e0e3820',
    messagingSenderId: '875525409377',
    projectId: 'aula0910-efa77',
    authDomain: 'aula0910-efa77.firebaseapp.com',
    storageBucket: 'aula0910-efa77.firebasestorage.app',
    measurementId: 'G-C8C106LC9N',
  );
}
